### ISSUE TITLE
How have the following constants been derived?

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [plepers/nanogl-pbr#5]
Hi,

Thank you for NanoGL and all its components, it has been a great source of inspiration for me 👍 

I was reading through the case study of For Honor (https://m.makemepulse.com/behind-the-scenes-of-for-honor-scars-cbb800c6e05f) and came across this section on encoding different levels of gloss. How exactly have the following constants been derived?

https://github.com/plepers/nanogl-pbr/blob/1580de8043ba16780a0d355ae4f4430fce92d64b/bin/nanoglibl#L73-L79

For example: lets say gloss level `6`:

`ANGLE=$( bc <<< "10 + 80/7 * $LVL" )`
Where `$LVL` is `6` returns `76`. 

Passing $ANGLE in `bc -l <<< "l( l( 0.00001 ) / l( c( ($ANGLE)/180.0*3.14159265 ) ) ) / l(2)"` results in `3.02016529742223291676`, not `3.9191797055252344`.

Am I missing something?

Many thanks in advance,

Tim

**Comment by plepers** [comment]
Hi,

I put the draft script i used back then to generate those constants.

https://gist.github.com/plepers/d4eaebe676007b302eec7977118df5ff

I use marmoset toolbag to prototype stuff. Those constant are made to match how marmoset compute specular power, which seems pretty uncommon for me btw...

I seen many other way to compute this spec power across engines, so your routine is probably as good as mine :)

**Comment by TimvanScherpenzeel** [comment]
👍 Thanks for the clarification. I wasn't aware of Marmoset, it looks really interesting!
